# Generated by Django 3.2.5 on 2021-07-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='page',
            field=models.CharField(default='context', max_length=30),
        ),
    ]
