# Generated by Django 3.2.5 on 2021-07-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_state_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='page',
            field=models.CharField(max_length=30),
        ),
    ]
